version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db

  backend:
    image: shivamyawlkar/backend:latest
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/appdb

  frontend:
    image: shivamyawlkar/frontend:latest

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: