name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
           set -e

            export DEBIAN_FRONTEND=noninteractive
            
            sudo apt update -y
            sudo apt install -y docker.io containerd docker-compose-v2 || true
            
            sudo systemctl daemon-reload
            
            # Start containerd first
            if ! sudo systemctl enable --now containerd; then
              echo "=== containerd failed ==="
              sudo systemctl status containerd --no-pager || true
              sudo journalctl -u containerd --no-pager -n 200 || true
              exit 1
            fi
            
            # Start docker, if fails print full logs and exit
            if ! sudo systemctl enable --now docker; then
              echo "=== docker failed ==="
              sudo systemctl status docker --no-pager || true
              sudo journalctl -u docker --no-pager -n 200 || true
            
              echo "=== extra diagnostics ==="
              sudo ls -la /etc/docker || true
              sudo cat /etc/docker/daemon.json || true
              sudo dmesg | tail -n 80 || true
              exit 1
            fi
            
            docker --version
            docker compose version
                        
                        docker compose pull
            docker compose up -d
            docker ps
