name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
           set -e

            # 0) Stop docker if running (ignore errors)
            sudo systemctl stop docker || true
            
            # 1) Remove Docker official repo (so it won't try installing containerd.io)
            sudo rm -f /etc/apt/sources.list.d/docker.list || true
            sudo rm -f /etc/apt/keyrings/docker.gpg || true
            
            # 2) Remove conflicting docker packages (safe to re-run)
            sudo apt remove -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-compose || true
            sudo apt remove -y containerd runc || true
            
            # 3) Clean apt state
            sudo apt update -y
            sudo apt --fix-broken install -y || true
            
            # 4) Install from Ubuntu repo ONLY (stable on 24.04)
            sudo apt install -y docker.io containerd docker-compose-v2 git
            
            # 5) Start docker
            sudo systemctl enable docker
            sudo systemctl start docker
            
            # Start docker (if fails, print logs and exit)
            if ! sudo systemctl enable --now docker; then
              echo "=== Docker service failed. Showing status & logs ==="
              sudo systemctl status docker --no-pager || true
              sudo journalctl -u docker --no-pager -n 200 || true
              exit 1
            fi

            if ! sudo systemctl enable --now containerd; then
            echo "=== containerd service failed. Showing status & logs ==="
            sudo systemctl status containerd --no-pager || true
            sudo journalctl -u containerd --no-pager -n 200 || true
            exit 1
            fi
            
            # 6) Verify
            docker --version
            docker compose version
            
            # 7) Deploy
            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app
            
            if [ ! -f docker-compose.yml ]; then
              git clone https://github.com/Shivam-yaw/fullstack-docker-aws-deployment.git .
            else
              git pull
            fi
            
            docker compose pull
            docker compose up -d
            docker ps
